from .activity_log import router as activity_log_router
from .ambulance import router as ambulance_router
from .api_key import router as api_key_router
from .appointment import router as appointment_router
from .attendance import router as attendance_router
from .audit_log import router as audit_log_router
from .base import router as base_router
from .bed import router as bed_router
from .billing import router as billing_router
from .chat import router as chat_router
from .complaint import router as complaint_router
from .department import router as department_router
from .diagnosis import router as diagnosis_router
from .doctor import router as doctor_router
from .event import router as event_router
from .feedback import router as feedback_router
from .inventory import router as inventory_router
from .notification import router as notification_router
from .nurse import router as nurse_router
from .patient import router as patient_router
from .pharmacy import router as pharmacy_router
from .prescription import router as prescription_router
from .radiology import router as radiology_router
from .user import router as user_router
from .ward import router as ward_router
from .faq import router as faq_router
from .feedback import router as feedback_router
from .imaging import router as imaging_router
from .insurance import router as insurance_router
from .lab_report import router as lab_report_router
from .lab_test import router as lab_test_router
from .leave import router as leave_router
from .medical_record import router as medical_record_router
from .medicine import router as medicine_router
from .message import router as message_router
from .payment import router as payment_router
from .payroll import router as payroll_router
from .procedure import router as procedure_router
from .purchase_order import router as purchase_order_router
from .role import router as role_router
from .role_permission import router as role_permission_router
from .schedule import router as schedule_router
from .setting import router as setting_router
from .shift import router as shift_router
from .stock import router as stock_router
from .supplier import router as supplier_router
from .transport import router as transport_router
from .vendor import router as vendor_router



# ... add others as needed
