"""
Billing Schemas - Pydantic V2
Billing and invoice management
"""

from typing import Optional, List, Dict, Any
from pydantic import Field, field_validator, model_validator
from datetime import datetime
from decimal import Decimal

from .base import BaseSchema, BaseResponseSchema


# ============================================
# Billing Item Schema
# ============================================

class BillingItem(BaseSchema):
    """Schema for individual billing item"""
    
    description: str = Field(..., min_length=2, max_length=200)
    quantity: int = Field(default=1, ge=1)
    unit_price: Decimal = Field(..., ge=0)
    total_price: Decimal = Field(..., ge=0)
    item_type: str = Field(default='service', description="service, medicine, test, procedure")
    
    @model_validator(mode='after')
    def validate_total(self):
        """Validate total price calculation"""
        calculated_total = self.quantity * self.unit_price
        if abs(self.total_price - calculated_total) > Decimal('0.01'):
            raise ValueError("Total price must equal quantity × unit price")
        return self


# ============================================
# Billing Create
# ============================================

class BillingCreate(BaseSchema):
    """Schema for creating billing/invoice"""
    
    patient_id: int = Field(..., description="Patient ID")
    
    # Related Records
    admission_id: Optional[int] = None
    appointment_id: Optional[int] = None
    
    bill_type: str = Field(
        ...,
        description="outpatient, inpatient, emergency, diagnostic, pharmacy, procedure"
    )
    
    # Items (as JSON)
    bill_items: str = Field(..., description="JSON array of billing items")
    
    # Financial Details
    subtotal: Decimal = Field(..., ge=0)
    discount_percentage: Decimal = Field(default=Decimal('0.00'), ge=0, le=100)
    discount_amount: Decimal = Field(default=Decimal('0.00'), ge=0)
    tax_percentage: Decimal = Field(default=Decimal('0.00'), ge=0, le=100)
    tax_amount: Decimal = Field(default=Decimal('0.00'), ge=0)
    total_amount: Decimal = Field(..., ge=0)
    
    # Payment
    payment_status: str = Field(default='pending')
    
    # Insurance
    insurance_id: Optional[int] = None
    insurance_claim_amount: Optional[Decimal] = Field(default=None, ge=0)
    
    # Due Date
    due_date: Optional[str] = Field(default=None, description="YYYY-MM-DD")
    
    # Notes
    notes: Optional[str] = Field(default=None, max_length=2000)
    terms_conditions: Optional[str] = Field(default=None, max_length=2000)
    
    # Generated By
    generated_by: Optional[str] = Field(default=None, max_length=200)
    
    @field_validator('bill_type')
    @classmethod
    def validate_bill_type(cls, v: str) -> str:
        """Validate bill type"""
        allowed = [
            'outpatient', 'inpatient', 'emergency', 'diagnostic',
            'pharmacy', 'procedure', 'surgery', 'lab'
        ]
        if v.lower() not in allowed:
            raise ValueError(f'Bill type must be one of: {", ".join(allowed)}')
        return v.lower()
    
    @field_validator('payment_status')
    @classmethod
    def validate_payment_status(cls, v: str) -> str:
        """Validate payment status"""
        allowed = ['pending', 'partial', 'paid', 'overdue', 'cancelled']
        if v.lower() not in allowed:
            raise ValueError(f'Payment status must be one of: {", ".join(allowed)}')
        return v.lower()
    
    @model_validator(mode='after')
    def validate_amounts(self):
        """Validate amount calculations"""
        # Validate discount
        if self.discount_percentage > 0:
            calculated_discount = (self.subtotal * self.discount_percentage) / 100
            if abs(self.discount_amount - calculated_discount) > Decimal('0.01'):
                raise ValueError("Discount amount must match discount percentage")
        
        # Validate tax
        taxable = self.subtotal - self.discount_amount
        if self.tax_percentage > 0:
            calculated_tax = (taxable * self.tax_percentage) / 100
            if abs(self.tax_amount - calculated_tax) > Decimal('0.01'):
                raise ValueError("Tax amount must match tax percentage")
        
        # Validate total
        calculated_total = self.subtotal - self.discount_amount + self.tax_amount
        if abs(self.total_amount - calculated_total) > Decimal('0.01'):
            raise ValueError("Total amount calculation incorrect")
        
        return self


# ============================================
# Billing Update
# ============================================

class BillingUpdate(BaseSchema):
    """Schema for updating billing"""
    
    payment_status: Optional[str] = None
    amount_paid: Optional[Decimal] = Field(default=None, ge=0)
    
    insurance_claim_amount: Optional[Decimal] = Field(default=None, ge=0)
    insurance_approved_amount: Optional[Decimal] = Field(default=None, ge=0)
    insurance_status: Optional[str] = None
    
    due_date: Optional[str] = None
    status: Optional[str] = None
    notes: Optional[str] = Field(default=None, max_length=2000)


# ============================================
# Billing Response
# ============================================

class BillingResponse(BaseResponseSchema):
    """Schema for billing response"""
    
    invoice_number: str
    invoice_date: str
    
    patient_id: int
    admission_id: Optional[int] = None
    appointment_id: Optional[int] = None
    
    bill_type: str
    bill_items: str  # JSON string
    
    subtotal: Decimal
    discount_percentage: Decimal
    discount_amount: Decimal
    tax_percentage: Decimal
    tax_amount: Decimal
    total_amount: Decimal
    
    payment_status: str
    amount_paid: Decimal
    amount_due: Decimal
    
    insurance_id: Optional[int] = None
    insurance_claim_amount: Optional[Decimal] = None
    insurance_approved_amount: Optional[Decimal] = None
    insurance_status: Optional[str] = None
    
    due_date: Optional[str] = None
    status: str
    
    generated_by: Optional[str] = None
    
    @property
    def is_overdue(self) -> bool:
        """Check if bill is overdue"""
        if self.due_date and self.payment_status != 'paid':
            from datetime import datetime
            try:
                due = datetime.strptime(self.due_date, '%Y-%m-%d').date()
                return datetime.now().date() > due
            except:
                return False
        return False


class BillingListResponse(BaseSchema):
    """Schema for billing list response"""
    
    id: int
    invoice_number: str
    invoice_date: str
    patient_id: int
    bill_type: str
    total_amount: Decimal
    amount_paid: Decimal
    amount_due: Decimal
    payment_status: str
    status: str
    created_at: datetime


class BillingDetailResponse(BillingResponse):
    """Detailed billing response"""
    
    patient_name: str
    patient_phone: str
    patient_email: Optional[str] = None
    
    bill_items_parsed: List[Dict[str, Any]] = []  # Parsed JSON items
    
    payments: List[Dict[str, Any]] = []  # Associated payments
    
    insurance_provider: Optional[str] = None


# ============================================
# Exports
# ============================================

__all__ = [
    "BillingItem",
    "BillingCreate",
    "BillingUpdate",
    "BillingResponse",
    "BillingListResponse",
    "BillingDetailResponse",
]