"""
Billing Model
Patient billing and invoice management
"""

from sqlalchemy import Column, Integer, String, Text, Boolean, ForeignKey, Index, CheckConstraint, Numeric
from sqlalchemy.orm import relationship, Mapped, mapped_column, validates
from typing import Optional, List
from decimal import Decimal

from .base import BaseModel


class Billing(BaseModel):
    """
    Patient billing and invoice model
    """
    
    __tablename__ = "billings"
    
    # Invoice Details
    invoice_number: Mapped[str] = mapped_column(String(20), unique=True, nullable=False, index=True)
    invoice_date: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    
    # Patient
    patient_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Related Records
    admission_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("admissions.id", ondelete="SET NULL"),
        index=True
    )
    appointment_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("appointments.id", ondelete="SET NULL")
    )
    
    # Bill Type
    bill_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="outpatient, inpatient, emergency, diagnostic, pharmacy, procedure"
    )
    
    # Items (JSON format)
    bill_items: Mapped[str] = mapped_column(Text, nullable=False, comment="JSON array of billing items")
    
    # Financial Details
    subtotal: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    discount_percentage: Mapped[Decimal] = mapped_column(Numeric(5, 2), default=Decimal('0.00'))
    discount_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal('0.00'))
    tax_percentage: Mapped[Decimal] = mapped_column(Numeric(5, 2), default=Decimal('0.00'))
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal('0.00'))
    total_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    
    # Payment Status
    payment_status: Mapped[str] = mapped_column(
        String(20),
        default='pending',
        nullable=False,
        index=True,
        comment="pending, partial, paid, overdue, cancelled"
    )
    amount_paid: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal('0.00'))
    amount_due: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    
    # Insurance
    insurance_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("insurances.id", ondelete="SET NULL")
    )
    insurance_claim_amount: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2))
    insurance_approved_amount: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2))
    insurance_status: Mapped[Optional[str]] = mapped_column(
        String(20),
        comment="pending, approved, rejected, partially_approved"
    )
    
    # Due Date
    due_date: Mapped[Optional[str]] = mapped_column(String(20), index=True)
    
    # Status
    status: Mapped[str] = mapped_column(
        String(20),
        default='active',
        nullable=False,
        index=True,
        comment="active, cancelled, refunded, void"
    )
    
    # Generated By
    generated_by: Mapped[Optional[str]] = mapped_column(String(200))
    
    # Notes
    notes: Mapped[Optional[str]] = mapped_column(Text)
    terms_conditions: Mapped[Optional[str]] = mapped_column(Text)
    
    # Relationships
    patient: Mapped["Patient"] = relationship(
        "Patient",
        back_populates="billings"
    )
    
    admission: Mapped[Optional["Admission"]] = relationship(
        "Admission",
        backref="billings"
    )
    
    appointment: Mapped[Optional["Appointment"]] = relationship(
        "Appointment",
        backref="billings"
    )
    
    insurance: Mapped[Optional["Insurance"]] = relationship(
        "Insurance",
        backref="billings"
    )
    
    payments: Mapped[List["Payment"]] = relationship(
        "Payment",
        back_populates="billing",
        lazy="dynamic"
    )
    
    # Table Arguments
    __table_args__ = (
        CheckConstraint('subtotal >= 0', name='billing_positive_subtotal'),
        CheckConstraint('discount_amount >= 0', name='billing_positive_discount'),
        CheckConstraint('tax_amount >= 0', name='billing_positive_tax'),
        CheckConstraint('total_amount >= 0', name='billing_positive_total'),
        CheckConstraint('amount_paid >= 0', name='billing_positive_paid'),
        CheckConstraint('amount_due >= 0', name='billing_positive_due'),
        Index('idx_billing_patient', 'patient_id', 'invoice_date'),
        Index('idx_billing_payment_status', 'payment_status', 'status'),
        Index('idx_billing_due_date', 'due_date', 'payment_status'),
        {'comment': 'Patient billing and invoice management'}
    )
    
    # Validators
    @validates('bill_type')
    def validate_bill_type(self, key, value):
        valid_types = [
            'outpatient', 'inpatient', 'emergency', 'diagnostic',
            'pharmacy', 'procedure', 'surgery', 'lab'
        ]
        if value.lower() not in valid_types:
            raise ValueError(f"Bill type must be one of: {', '.join(valid_types)}")
        return value.lower()
    
    @validates('payment_status')
    def validate_payment_status(self, key, value):
        valid_statuses = ['pending', 'partial', 'paid', 'overdue', 'cancelled']
        if value.lower() not in valid_statuses:
            raise ValueError(f"Payment status must be one of: {', '.join(valid_statuses)}")
        return value.lower()
    
    @validates('status')
    def validate_status(self, key, value):
        valid_statuses = ['active', 'cancelled', 'refunded', 'void']
        if value.lower() not in valid_statuses:
            raise ValueError(f"Status must be one of: {', '.join(valid_statuses)}")
        return value.lower()
    
    @property
    def is_overdue(self) -> bool:
        """Check if payment is overdue"""
        from datetime import datetime
        if self.due_date and self.payment_status != 'paid':
            try:
                due = datetime.strptime(self.due_date, '%Y-%m-%d')
                return datetime.now() > due
            except:
                return False
        return False
    
    def __repr__(self) -> str:
        return f"<Billing(id={self.id}, invoice='{self.invoice_number}', amount={self.total_amount}, status='{self.payment_status}')>"